### ISSUE TITLE
Upgrading tier I lose the content of the pocket

### ISSUE THREAD

**Issue by JisuCraft** [Flanks255/pocketstorage#34] opened 2024-08-16 17:30 UTC
Hi!

I'm playing ATM10 (1.21.1) . 
I have upgraded from TIER 1 to TIER 2 and I have lost all the items inside the pocket.

**Comment by Flanks255** [comment] 2024-08-16 17:59
Hey, so, does ATM change the recipe at all? this is the normal tier 2 upgrade recipe.
![image](https://github.com/user-attachments/assets/3e4b6375-6ac4-4456-840a-f414203e3f23)

What crafting interface was it done in? ive seen a few times where someone used an auto crafter, or a AE2 interface which bypassed the recipe before.

**Comment by Flanks255** [comment] 2024-08-16 18:01
in the meantime, you(or a op on the server if you are in multiplayer) can use the /ps list, command to find your pocket storage and recover it.

**Comment by JisuCraft** [comment] 2024-08-16 18:21
> Hey, so, does ATM change the recipe at all? this is the normal tier 2 upgrade recipe. ![image](https://private-user-images.githubusercontent.com/32142731/358670239-3e4b6375-6ac4-4456-840a-f414203e3f23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MzE0ODYsIm5iZiI6MTcyMzgzMTE4NiwicGF0aCI6Ii8zMjE0MjczMS8zNTg2NzAyMzktM2U0YjYzNzUtNmFjNC00NDU2LTg0MGEtZjQxNDIwM2UzZjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE3NTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OWUyMjJmYjc4Y2NiM2Q0MGNmNzJkYWMyNzNiNzJjOGVmZDZhMjA4MjEyMWYxZWRkMWYxOTQ0YjRlNGUwMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDnMAvWUsbpBZmGqMVKt_fqjMC80ZfnhnJplamKcWgM)
> 
> What crafting interface was it done in? ive seen a few times where someone used an auto crafter, or a AE2 interface which bypassed the recipe before.

Hi! Yes, that's the recipe. I used a crafting on a stick located on his curios slot. I clicked the (+) button on the interface to load the recipe auto.
I have made some tests in a creative world, ans I think that only fails the tier 1 to tier 2 upgrade.... but not always... I thinks that works fine if I put the recipe manually in the table, and fails when I "auto-load" it with the (+) button of the JEI (I think that it's not JEI, it's EMI, an alternative)

**Comment by Flanks255** [comment] 2024-08-16 19:14
huh, interesting, if you do more experiments, can you see if the tooltip in the source pocket storage still shows its ID, and if the resulting pocket storage has a ID in the tooltip?

i havnt been able to get it to happen on my end yet.

**Comment by JisuCraft** [comment] 2024-08-16 19:46
Hi again.... I have good news, and bad news.... I've been trying again, with tooltips shown to check the IDs, but I haven't been able to reproduce the issue again :/

I'm sorry If I made you lose your time... :(

**Comment by Flanks255** [comment] 2024-08-16 22:12
its all good, if you can ever get it to happen again and get any details let me know👍

**Comment by billyty08** [comment] 2024-08-26 18:09
I just had the same thing happen on AlltheMods10.Thanks for the /ps tip. I used vanilla crafting table and clicked + to fill craft as well. the pic is the contents and the recipe shown. It did have an or dict for the chests but I used vanilla mc chests
![Screenshot 2024-08-26 130432](https://github.com/user-attachments/assets/660acbed-25e4-4aa8-9f34-6898ac3572e6)
![Screenshot 2024-08-26 130559](https://github.com/user-attachments/assets/b46734e9-624a-46f6-82c8-db06657943d5)

**Comment by Flanks255** [comment] 2024-08-26 19:46
Whats EMI?

**Comment by Flanks255** [comment] 2024-08-26 21:46
Ok, so i cant reproduce this with just my mod and JEI/EMI, but something in ATM10 is messing with the recipe..., cause i installed ATM10, and sure enough, doesnt work when autofilled...

**Comment by TheIllusiveC4** [comment] 2024-08-27 20:16
You can reproduce the issue with this mod, FastWorkbench, EMI, and Polymorph. The combination of Polymorph and EMI makes the issue more visible but a variant of this also appears with just FastWorkbench installed alongside this mod. If you have two separate T1 units and place one of them in a T2 recipe, the output will be correct. However, if you then directly swap the T1 unit in the recipe (without removing anything) with the other one, then the output's ID will remain the same as the previous one and not update to match the current one. This is not the behavior when the mod is by itself.

After further investigation, I believe the issue comes from this line in FastWorkbench that is preventing some stack updates from propagating:
https://github.com/Shadows-of-Fire/FastWorkbench/blob/1.21/src/main/java/dev/shadowsoffire/fastbench/util/FastBenchUtil.java#L68
It looks like it needs to be updated from `recipe.getClass()` to `recipe.value().getClass()`.

**Comment by Flanks255** [comment] 2024-08-28 17:25
@billyty08 @JisuCraft could you try updatting fastworkbench to 9.1.2 in your pack and see if that fixes the issue?

**Comment by billyty08** [comment] 2024-08-29 00:12
I had to manually add it because CF launcher didn't list 9.1.2 to update fastbench but everything appears to be working now. Thank you for all the hard work you put into mods for our enjoyment!!

**Comment by Flanks255** [comment] 2024-08-29 23:00
> I had to manually add it because CF launcher didn't list 9.1.2 to update fastbench but everything appears to be working now. Thank you for all the hard work you put into mods for our enjoyment!!

ya, i dont think shadows marked it as 1.21.1 yet lol, but glad we got this figured out. :)

**Closed by Flanks255** 2024-08-29 23:00 UTC
